source 'https://rubygems.org'
# created by inline_forms 5.2.4 on {Date.today}

gem 'cancancan', '~> 2.0'
gem 'carrierwave'
gem 'ckeditor', git: 'https://github.com/galetahub/ckeditor'
gem 'coffee-rails'
gem 'compass-rails'
gem 'devise'
gem 'foundation-icons-sass-rails'
gem 'foundation-rails', '~> 5.5'
gem 'i18n-active_record', git: 'https://github.com/acesuares/i18n-active_record.git'
gem 'inline_forms', '>=5'
gem 'jquery-rails'
gem 'jquery-timepicker-rails'
gem 'jquery-ui-sass-rails'
gem 'mini_magick'
gem 'mysql2'
gem 'paper_trail'
gem 'rails-i18n'
gem 'rails', '~> 5.2.1'
gem 'rake'
gem 'remotipart', '~> 1.0'
gem 'rvm'
gem 'sass-rails'
gem 'tabs_on_rails'
gem 'therubyracer'
gem 'uglifier'
gem 'figaro'
gem 'unicorn'
gem 'validation_hints'
gem 'will_paginate'
gem 'turbolinks', '~> 5'
group :development do
  gem 'bundler'
  gem 'listen'
  gem 'rspec-rails'
  gem 'rspec'
  gem 'seed_dump', git: 'https://github.com/acesuares/seed_dump.git'
  gem 'shoulda'
  gem 'sqlite3'
  gem 'switch_user'
  gem 'yaml_db'
  gem 'capistrano', '~> 3.6', require: false
  gem 'capistrano-rails', '~> 1.3', require: false
  gem 'capistrano-bundler', '~> 1.3', require: false
  gem 'rvm1-capistrano3', require: false
  gem 'capistrano3-unicorn'
end
